### ISSUE TITLE
GTK4

### ISSUE THREAD

**Issue by Tsohndeq** [japajoe/GtkSharp#1]
Would be better to focus on newer version of GTK while this project is still on starting stage? Because of complicity, original GtkSharp is stucked with 3 version, when 4 version can provide many benefits such as Vulkan GPU rendering etc.

**Comment by japajoe** [comment]
That is an interesting point you make although there are some reasons why this is not viable for me to do this right now. The biggest reason is my total lack of experience with GTK4. It's already quite the challenge to make this library, so having to do it with something I am not familiar with does not benefit anyone. However, I can totally understand why GPU rendering would be useful, but I don't want to make promises with regards to this. There is already another mature GtkSharp project which I don't even try to compete with, but it's also still on GTK3. First and foremost I started this to develop a better understanding in interoperability between programming languages, second to have a UI library for my own projects. I consider it an honor that you and others are willing to try it out and I'll do my best to make it as useful as I can.
